untitled/src/objects/Application__c.object
<CustomObject>
    <description>Application Object to list all the Applications</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to Application</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IndividualApplicant__c</fullName>
        <description>Application (Child Object) with a Master - Detail relationship to IndividualApplicant (Parent Object)</description>
        <label>IndividualApplicant</label>
        <referenceTo>IndividualApplicant__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JobPosting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Applications(Child Object) with a Lookup to JobPosting ( Parent Object)</description>
        <label>JobPosting</label>
        <referenceTo>JobPostings__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

untitled/src/objects/IndividualApplicant__c.object
<CustomObject>
    <description>Individual Applicant object is to list all the Applicants records.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Id of Applicant</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>IndividualApplicant</label>
    <nameField>
        <label>Individual Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IndividualApplicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

untitled/src/objects/JobPostings__c.object
<CustomObject>
    <description>Job Postings Object to  list positions</description>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>JobPosting</label>
    <nameField>
        <label>JobPostings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JobPostings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

untitled/src/classes/RestAPI_createApplications.cls
@RestResource(urlMapping = '/Applications/*')
global class RestAPI_createApplications {
    
    global class ApplicationsWrapper {
    public String Name;
    public String Email;
    public String Address;
    public String Phone;
    public String JobId;
    

    public Application__c getApp() {
        
        return new Application__c(
            Name = this.Name,
            Email__c = this.Email,
            Address__c = this.Address,
            Phone__c = this.Phone,
            Job_Id__c = this.JobId
        );
    }
}
    
    @HttpPost
    global static void insertApp(List<ApplicationsWrapper> webformData) {
        List<Application__c> AppstoCreate = new List<Application__c>();
        List<String> Jobids = new List<String>();
        List<String> Emails = new List<String>();
        
        for(ApplicationsWrapper App :webformData ){
           AppstoCreate.add(App.getApp()) ;
            Jobids.add(App.getApp().Job_Id__c);
            Emails.add(App.getApp().Email__c);
        }
        
        List<JobPostings__c> JobPostList = [SELECT Id,Job_Id__c FROM JobPostings__c WHERE Job_Id__c IN:Jobids ];
        List<Contact> ConList = [SELECT Id,Name,Email FROM Contact WHERE Email IN:Emails ];
        List<IndividualApplicant__c> IndAppList = [SELECT Id,Name,Email__c FROM IndividualApplicant__c WHERE Email__c IN:Emails ];
        for(Application__c App:AppstoCreate){
            for(JobPostings__c JobPosting : JobPostList){
                if(JobPosting.Job_Id__c == App.Job_Id__c && JobPosting != null)
              App.JobPosting__c =  JobPosting.Id; 
            } 
            for(Contact Con : ConList){
                if(Con.Email ==App.Email__c && Con!= null)
               App.Contact__c =  Con.Id;      
            }
            for(IndividualApplicant__c IndApp : IndAppList){
                if(IndApp.Email__c ==App.Email__c && IndApp != null )
               App.IndividualApplicant__c =  IndApp.Id;      
            }
        }
        Insert AppstoCreate;    
    }
    
}