untitled/src/objects/Application__c.object
<CustomObject>
    <description>Application Object to list all the Applications</description>
    <fields>
        <fullName>ActiveApplication__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Acitve Applications</description>
        <label>ActiveApplication</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobPosting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Applications(Child Object) with a Lookup to JobPosting ( Parent Object)</description>
        <label>JobPosting</label>
        <referenceTo>JobPostings__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

untitled/src/objects/JobPostings__c.object
<CustomObject>
    <description>Job Postings Object to  list positions</description>
    <fields>
        <fullName>Active_Job__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active Jobs</description>
        <label>Active Job</label>
        <type>Checkbox</type>
    </fields>
    <label>JobPosting</label>
    <nameField>
        <label>JobPostings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JobPostings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

untitled/src/classes/JobPostingTriggerHandler.cls
public class JobPostingTriggerHandler {
  public void afterUpdate(List<JobPostings__c> oldjobpostings,List<JobPostings__c> newjobpostings)
    {
        Set<Id> jpstids = new Set<Id>();
        for(JobPostings__c jpc: newjobpostings){
		if(jpc.Active_Job__c == false)
            jpstids.add(jpc.Id);
        }
        List<Application__c> updjpLst = new List<Application__c>();
        for(Application__c jps:[SELECT Id,ActiveApplication__c,JobPosting__c FROM Application__c WHERE JobPosting__c IN: jpstids ]){
            jps.ActiveApplication__c = false;
            updjpLst.add(jps);
        }
        Update updjpLst;
}
}