untitled/src/objects/Application__c.object
<CustomObject>
    <description>Application Object to list all the Applications</description>
    <fields>
        <fullName>ActiveApplication__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Acitve Applications</description>
        <label>ActiveApplication</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IndividualApplicant__c</fullName>
        <description>Application (Child Object) with a Master - Detail relationship to IndividualApplicant (Parent Object)</description>
        <label>IndividualApplicant</label>
        <referenceTo>IndividualApplicant__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JobPosting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Applications(Child Object) with a Lookup to JobPosting ( Parent Object)</description>
        <label>JobPosting</label>
        <referenceTo>JobPostings__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

untitled/src/objects/IndividualApplicant__c.object
<CustomObject>
    <description>Individual Applicant object is to list all the Applicants records.</description>
    <label>IndividualApplicant</label>
    <nameField>
        <label>Individual Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IndividualApplicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

untitled/src/objects/JobPostings__c.object
<CustomObject>
    <description>Job Postings Object to  list positions</description>
    <fields>
        <fullName>Active_Job__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active Jobs</description>
        <label>Active Job</label>
        <type>Checkbox</type>
    </fields>
    <label>JobPosting</label>
    <nameField>
        <label>JobPostings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JobPostings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

untitled/src/classes/JobPostingTriggerHandlerTest.cls
@isTest
public class JobPostingTriggerHandlerTest {
    
    @isTest static void Testupdatestatusfield() {
        IndividualApplicant__c IndAppcnt = new IndividualApplicant__c(Name= 'Test');
        insert IndAppcnt;
        
        JobPostings__c Jp = new JobPostings__c(Name='TestJobPosting',Active_Job__c = true);
        insert Jp;
        
        Application__c App = new Application__c(Name='TestApplicantion',IndividualApplicant__c=IndAppcnt.Id, ActiveApplication__c=true,JobPosting__c =Jp.Id);
		insert App;
                
        Jp.Active_Job__c = false;
              
        Test.startTest();       
        Update Jp;
        Test.stopTest();
        
    }
                      
}