untitled/src/objects/Application__c.object
<CustomObject>
    <description>Application Object to list all the Applications</description>
    <fields>
        <fullName>ActiveApplication__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Acitve Applications</description>
        <label>ActiveApplication</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IndividualApplicant__c</fullName>
        <description>Application (Child Object) with a Master - Detail relationship to IndividualApplicant (Parent Object)</description>
        <label>IndividualApplicant</label>
        <referenceTo>IndividualApplicant__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JobPosting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Applications(Child Object) with a Lookup to JobPosting ( Parent Object)</description>
        <label>JobPosting</label>
        <referenceTo>JobPostings__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

untitled/src/objects/IndividualApplicant__c.object
<CustomObject>
    <description>Individual Applicant object is to list all the Applicants records.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Id of Applicant</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>IndividualApplicant</label>
    <nameField>
        <label>Individual Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IndividualApplicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

untitled/src/objects/JobPostings__c.object
<CustomObject>
    <description>Job Postings Object to  list positions</description>
    <fields>
        <fullName>Active_Job__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active Jobs</description>
        <label>Active Job</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>JobPosting</label>
    <nameField>
        <label>JobPostings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JobPostings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

untitled/src/classes/AllActiveJobPosting.cls
Public class AllActiveJobPosting {
    private ApexPages.StandardController Controller {get; set;}
    public list<JobPostings__c> jobpostings {get; set;}
    public list<Jpwrapper> jpwrapperlist {get; set;}
    public list<JobPostings__c> clickedjobpostings {get; set;}
    public list<Application__c> linkedapplication {get; set;}
    public list<IndividualApplicant__c> linkedIndividualApplicant {get; set;}
    
    public AllActiveJobPosting(ApexPages.StandardController controller){
        this.controller = controller;
        if(jpwrapperlist == null){
            jpwrapperlist = new list<Jpwrapper>();
            for(JobPostings__c jpc :[Select Id,Name,Job_Id__c,Active_Job__c from JobPostings__c where Active_Job__c =True]){
                jpwrapperlist.add(new Jpwrapper(jpc));
            }
        }
        
    }
    public pagereference clicked(){
        clickedjobpostings = new list<JobPostings__c>();
        set<id> clickedjobids = new set<id>();
        
        for(Jpwrapper jpw : jpwrapperlist) {
            if(jpw.selected == true){
                clickedjobpostings.add(jpw.clickedjp);
                clickedjobids.add(jpw.clickedjp.id);
            }
        }
        linkedapplication = new list<Application__c>();
        for (Application__c apln:[select id,name,ActiveApplication__c,Email__c,IndividualApplicant__r.Name,IndividualApplicant__c,Job_Id__c,JobPosting__c,Phone__c from Application__c where JobPosting__c=:clickedjobids]){
            linkedapplication.add(apln);
        }
        return null; 
    }
        public class Jpwrapper {
            public JobPostings__c clickedjp{get;set;}
            public Boolean selected {get; set;}
            
            public Jpwrapper(JobPostings__c Jobp) {
                clickedjp = Jobp;
                selected = false;
            }
        }
    }